version: "3"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    network_mode: bridge
    ports: 4533:4533
    user: 1000:1000
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 10m
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/srv/share/media/music:/music:ro"
    restart: unless-stopped
